/** Studio Instrument supporting pages: calm editorial content with clear routes back to working tools. */
import { ArrowRight, Mail, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import AppShell from "@/components/AppShell";
import PublisherReserve from "@/components/PublisherReserve";
import { barcodeMeta, qrTypeMeta, type BarcodeFormat, type QRType } from "@/lib/code-utils";

const qrTypes = Object.keys(qrTypeMeta) as QRType[];
const barcodeTypes = Object.keys(barcodeMeta) as BarcodeFormat[];

const faqs = [
  ["Is the QR code generator free?", "Yes. The core generator works in the browser without an account or paid API."],
  ["Do I need an account?", "No. You can generate, export, print, and save local favorites without signing in."],
  ["Can I download QR codes?", "Yes. The QR studio supports PNG, SVG, and JPG outputs. Barcode exports use the same formats where the browser can render them reliably."],
  ["Can I print generated codes?", "Yes. The Print action opens a stripped-back proof with the generated code and its relevant label, ready for common paper sizes."],
  ["Are generated codes stored online?", "No. Payload creation and rendering happen in your browser. Optional history and favorites are saved only through your browser's local storage."],
  ["Which barcode formats are supported?", "The barcode studio supports CODE128, CODE39, EAN-13, EAN-8, UPC-A, ITF-14, ITF, MSI, and Pharmacode."],
];

function ArticleFrame({ kicker, title, children }: { kicker: string; title: React.ReactNode; children: React.ReactNode }) {
  return <AppShell><section className="info-hero"><p className="eyebrow"><span />{kicker}</p><h1>{title}</h1><div className="info-ruler" aria-hidden="true"><span>000</span><i /><span>032</span><i /><span>064</span><i /><span>096</span></div></section><section className="info-content"><div className="page-metadata"><span className="signal-dot" /><b>REFERENCE</b><i /> <span>CODE STUDIO NOTES</span><i /> <span>LOCAL-FIRST</span></div>{children}<PublisherReserve placement="Informational page reference area" /></section></AppShell>;
}

export function CodeTypesPage({ type }: { type: "qr" | "barcode" }) {
  const isQr = type === "qr";
  const items = isQr ? qrTypes : barcodeTypes;
  return <ArticleFrame kicker={isQr ? "QR payload guide" : "Barcode symbology guide"} title={isQr ? <>Find the QR format<br /><em>that carries your intent.</em></> : <>Choose the standard<br /><em>your label expects.</em></>}>
    <div className="type-page-intro"><p>{isQr ? "A QR code can carry more than a web address. Pick a payload type based on the action you want a scan to perform, then use the studio to validate and style it." : "Barcode standards are built around a specific use. Select the format specified by your product, inventory, shipping, or packaging workflow, then enter a valid identifier."}</p><Link href={isQr ? "/qr-generator" : "/barcode-generator"} className="primary-cta">Open {isQr ? "QR" : "barcode"} studio <ArrowRight size={17} /></Link></div>
    <div className="type-reference-grid">{items.map((item) => { const meta = isQr ? qrTypeMeta[item as QRType] : barcodeMeta[item as BarcodeFormat]; return <article key={item}><span>{isQr ? qrTypeMeta[item as QRType].symbol : "///"}</span><div><h2>{meta.label}</h2><p>{meta.description}</p><Link href={isQr ? "/qr-generator" : "/barcode-generator"}>Create this code <ArrowRight size={15} /></Link></div></article>; })}</div>
  </ArticleFrame>;
}

export function FAQPage() {
  return <ArticleFrame kicker="Support and guidance" title={<>Answers for the<br /><em>essential questions.</em></>}><div className="faq-page-grid"><p className="info-lead">The core tool is intentionally straightforward. These answers cover what happens to your data, the available outputs, and the standards currently supported.</p><Accordion type="single" collapsible className="faq-accordion">{faqs.map(([question, answer], index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent>{answer}</AccordionContent></AccordionItem>)}</Accordion><div className="support-note"><ShieldCheck size={22} /><p><b>Still need a hand?</b><span>For a specific workflow or a question about the tool, contact us with the code type and browser you are using.</span><Link href="/contact">Contact support <ArrowRight size={15} /></Link></p></div></div></ArticleFrame>;
}

export function AboutPage() { return <ArticleFrame kicker="About the studio" title={<>A quieter way to make<br /><em>codes that work.</em></>}><div className="article-copy"><p className="info-lead">QR &amp; Barcode Generator is a browser-native utility for the moments when a code needs to be accurate, clean, and ready to leave the screen.</p><h2>Why this tool exists</h2><p>Code generators often ask users to trade privacy for convenience or reduce an important output to a quick visual trick. This project takes the opposite position: creation should be direct, validation should be visible, and the information inside the code should stay under the creator’s control.</p><h2>Designed as a local instrument</h2><p>QR payloads and barcode values are encoded in the browser. Visual proofing, downloads, printing, and optional saved configurations are handled on the device you use. The result is a focused utility that works without an account or an unnecessary handoff of your information.</p><Link href="/qr-generator" className="primary-cta">Make a QR code <ArrowRight size={17} /></Link></div></ArticleFrame>; }

export function PrivacyPage() { return <ArticleFrame kicker="Privacy" title={<>Your code content<br /><em>does not need to travel.</em></>}><div className="article-copy"><p className="info-lead">The core QR and barcode generators are designed to work entirely in your browser.</p><h2>What remains local</h2><p>Your entered content, selected options, generated previews, downloaded files, print proofs, history, favorites, and theme preference are processed or stored by your browser on the device you are using. The application does not require a login or send your code payload to a generation API.</p><h2>Local history and favorites</h2><p>If you choose to export a code or save a favorite, a compact configuration is stored through browser local storage. You can reopen, delete, or clear these items at any time from the relevant generator workspace. Clearing your browser’s site data will also remove them.</p><h2>Logo uploads</h2><p>When you add an image as a QR logo, the image is read locally to prepare the preview. It is not uploaded by the generator.</p></div></ArticleFrame>; }

export function TermsPage() { return <ArticleFrame kicker="Terms of service" title={<>A practical tool,<br /><em>used thoughtfully.</em></>}><div className="article-copy"><p className="info-lead">Use the generator for lawful purposes and test important codes in their intended scanning environment before distribution.</p><h2>Output and verification</h2><p>You are responsible for the content you encode and for verifying that a generated code scans correctly in its final context. Print material, low-contrast colors, dense payloads, and oversized logos can affect scanning performance; the studio offers controls and warnings but cannot guarantee every downstream production condition.</p><h2>Acceptable use</h2><p>Do not use the application to create codes that facilitate fraud, malware delivery, unlawful data collection, or any other harmful or illegal activity. Do not represent the tool’s output as independently certified when you have not completed appropriate testing.</p><h2>Service changes</h2><p>The available formats and features may be refined as the browser-based tool evolves. Continued use means you accept the then-current presentation of the application.</p></div></ArticleFrame>; }

export function ContactPage() { return <ArticleFrame kicker="Contact" title={<>Let us know what<br /><em>you are trying to make.</em></>}><div className="contact-panel"><Mail size={26} /><div><p className="info-lead">For a question about an available code format, an accessibility concern, or feedback on the workflow, send a concise note with your browser and use case.</p><a href="mailto:hello@qrbarcodegenerator.example?subject=QR%20%26%20Barcode%20Generator%20question" className="primary-cta">Email the studio <ArrowRight size={17} /></a><p className="contact-fineprint">The email link opens your local mail application. Do not include sensitive personal data in support messages.</p></div></div></ArticleFrame>; }

export function QRUseCasePage({ kind }: { kind: "wifi" | "vcard" }) {
  const wifi = kind === "wifi";
  const title = wifi ? <>Share Wi-Fi details<br /><em>with one scan.</em></> : <>Put your contact<br /><em>in one scan.</em></>;
  const intro = wifi ? "A Wi-Fi QR code lets guests open their camera and join a network without typing the SSID or password. The details are assembled in your browser and remain on this device while you work." : "A vCard QR code packages a name, contact number, email address, website, organization, role, and address into a scan-ready contact card. It is useful when a printed item needs to lead directly to a saved contact.";
  return <ArticleFrame kicker={wifi ? "Wi-Fi QR code generator" : "vCard QR code generator"} title={title}><div className="article-copy use-case-copy"><p className="info-lead">{intro}</p><h2>{wifi ? "How to make a Wi-Fi QR code" : "How to make a vCard QR code"}</h2><p>{wifi ? "Choose Wi-Fi in the QR studio, enter the exact network name, select the security method, then add the password if the network is protected. Hidden networks can be marked before you create the proof." : "Choose Contact in the QR studio, enter at least a first or last name, then add the details you want a scanner to save. The form checks contact email addresses before creating the proof."}</p><h2>Check the final scan</h2><p>{wifi ? "Before distributing a code, test it with a device that is not already connected to the network. Keep the printed code high contrast and protect guest passwords appropriately." : "Before publishing, scan the printed or exported code on a separate device and confirm the contact fields land where expected. Keep the color contrast high and leave quiet space around the code."}</p><a href={`/qr-generator?type=${kind}`} className="primary-cta">Create {wifi ? "Wi-Fi" : "vCard"} QR code <ArrowRight size={17} /></a></div></ArticleFrame>;
}
